package net.macos.client.config;

import com.terraformersmc.modmenu.api.ConfigScreenFactory;
import com.terraformersmc.modmenu.api.ModMenuApi;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.BooleanControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.StringControllerBuilder;
import net.minecraft.text.Text;

public class ModMenuIntegration implements ModMenuApi {
    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        return parent -> {
            return YetAnotherConfigLib.createBuilder()
                    .title(Text.literal("MacClient Settings"))
                    .category(ConfigCategory.createBuilder()
                            .name(Text.literal("General"))
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Enable Glass Blur"))
                                    .description(OptionDescription.of(Text.literal("Enables macOS-style frosted glass blur effect.")))
                                    .binding(true, () -> ConfigManager.config.enableGlassBlur, val -> ConfigManager.config.enableGlassBlur = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.literal("Blur Radius"))
                                    .description(OptionDescription.of(Text.literal("Radius of the blur effect (20-30 recommended).")))
                                    .binding(20, () -> ConfigManager.config.blurRadius, val -> ConfigManager.config.blurRadius = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(10, 40).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.literal("Corner Radius"))
                                    .description(OptionDescription.of(Text.literal("Rounding of panel corners (12-16 recommended).")))
                                    .binding(12, () -> ConfigManager.config.cornerRadius, val -> ConfigManager.config.cornerRadius = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 24).step(1))
                                    .build())
                            .option(Option.<String>createBuilder()
                                    .name(Text.literal("Accent Color"))
                                    .description(OptionDescription.of(Text.literal("Hex color code for accents (e.g., #00D2FF).")))
                                    .binding("#00D2FF", () -> ConfigManager.config.accentColor, val -> ConfigManager.config.accentColor = val)
                                    .controller(StringControllerBuilder::create)
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Watermark"))
                                    .description(OptionDescription.of(Text.literal("Show nick, FPS, ping and time in top-left corner.")))
                                    .binding(true, () -> ConfigManager.config.enableWatermark, val -> ConfigManager.config.enableWatermark = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())                                    
                            .build())
                    .category(ConfigCategory.createBuilder()
                            .name(Text.literal("HUD Modules"))
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Target HUD"))
                                    .binding(true, () -> ConfigManager.config.enableTargetHUD, val -> ConfigManager.config.enableTargetHUD = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Armor Status Bar"))
                                    .binding(true, () -> ConfigManager.config.enableArmorBar, val -> ConfigManager.config.enableArmorBar = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Potion Effects Bar"))
                                    .binding(true, () -> ConfigManager.config.enablePotionEffects, val -> ConfigManager.config.enablePotionEffects = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Keystrokes Widget"))
                                    .binding(true, () -> ConfigManager.config.enableKeystrokesWidget, val -> ConfigManager.config.enableKeystrokesWidget = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Combo Counter"))
                                    .binding(true, () -> ConfigManager.config.enableComboCounter, val -> ConfigManager.config.enableComboCounter = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Attack Cooldown Indicator"))
                                    .description(OptionDescription.of(Text.literal("Shows a ring around the crosshair that fills as your attack recharges.")))
                                    .binding(true, () -> ConfigManager.config.enableAttackCooldown, val -> ConfigManager.config.enableAttackCooldown = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.literal("Cooldown Offset X"))
                                    .description(OptionDescription.of(Text.literal("Horizontal offset from crosshair (px).")))
                                    .binding(0, () -> ConfigManager.config.attackCooldownOffsetX, val -> ConfigManager.config.attackCooldownOffsetX = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(-50, 50).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.literal("Cooldown Offset Y"))
                                    .description(OptionDescription.of(Text.literal("Vertical offset from crosshair (px).")))
                                    .binding(0, () -> ConfigManager.config.attackCooldownOffsetY, val -> ConfigManager.config.attackCooldownOffsetY = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(-50, 50).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.literal("Cooldown Radius"))
                                    .description(OptionDescription.of(Text.literal("Radius of the cooldown ring (px).")))
                                    .binding(14, () -> ConfigManager.config.attackCooldownRadius, val -> ConfigManager.config.attackCooldownRadius = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(8, 40).step(1))
                                    .build())
                                                                .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Zoom (C)"))
                                    .description(OptionDescription.of(Text.literal("Hold C to zoom in.")))
                                    .binding(true, () -> ConfigManager.config.enableZoom, val -> ConfigManager.config.enableZoom = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.literal("Zoom FOV"))
                                    .description(OptionDescription.of(Text.literal("Target FOV when zooming (lower = stronger).")))
                                    .binding(20, () -> ConfigManager.config.zoomFov, val -> ConfigManager.config.zoomFov = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 50).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.literal("Zoom Speed"))
                                    .description(OptionDescription.of(Text.literal("How fast the zoom transitions.")))
                                    .binding(20, () -> ConfigManager.config.zoomSpeed, val -> ConfigManager.config.zoomSpeed = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 100).step(5))
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Fullbright"))
                                    .description(OptionDescription.of(Text.literal("Boost gamma to see in the dark.")))
                                    .binding(false, () -> ConfigManager.config.enableFullbright, val -> ConfigManager.config.enableFullbright = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.literal("Fullbright Gamma"))
                                    .description(OptionDescription.of(Text.literal("Gamma value when Fullbright is on (2-15 recommended).")))
                                    .binding(10, () -> ConfigManager.config.fullbrightGamma, val -> ConfigManager.config.fullbrightGamma = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(2, 20).step(1))
                                    .build())  
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("No Fog"))
                                    .description(OptionDescription.of(Text.literal("Removes fog in nether, water, blindness.")))
                                    .binding(false, () -> ConfigManager.config.enableNoFog, val -> ConfigManager.config.enableNoFog = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())   
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Auto Sprint"))
                                    .description(OptionDescription.of(Text.literal("Automatically sprint when moving forward.")))
                                    .binding(false, () -> ConfigManager.config.enableAutoSprint, val -> ConfigManager.config.enableAutoSprint = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Anti-AFK"))
                                    .description(OptionDescription.of(Text.literal("Periodically rotates camera to prevent AFK kicks. Use at your own risk!")))
                                    .binding(false, () -> ConfigManager.config.enableAntiAFK, val -> ConfigManager.config.enableAntiAFK = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())                                    
                                                                .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Waypoints"))
                                    .description(OptionDescription.of(Text.literal("Show waypoint markers with distance.")))
                                    .binding(true, () -> ConfigManager.config.enableWaypoints, val -> ConfigManager.config.enableWaypoints = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                                    
                            .build())
                    .category(ConfigCategory.createBuilder()
                            .name(Text.literal("Visuals & PvP"))
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Glass Chams"))
                                    .description(OptionDescription.of(Text.literal("Semi-transparent frosted glass effect on items and hands.")))
                                    .binding(false, () -> ConfigManager.config.enableGlassChams, val -> ConfigManager.config.enableGlassChams = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<String>createBuilder()
                                    .name(Text.literal("Hit Sound Preset"))
                                    .description(OptionDescription.of(Text.literal("Sound played on hit: default, pop, cod, apex, cs.")))
                                    .binding("default", () -> ConfigManager.config.hitSoundPreset, val -> ConfigManager.config.hitSoundPreset = val)
                                    .controller(StringControllerBuilder::create)
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Custom Crit Particles"))
                                    .binding(true, () -> ConfigManager.config.enableCustomCritParticles, val -> ConfigManager.config.enableCustomCritParticles = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.literal("Custom Kill Effects"))
                                    .binding(true, () -> ConfigManager.config.enableCustomKillEffects, val -> ConfigManager.config.enableCustomKillEffects = val)
                                    .controller(BooleanControllerBuilder::create)
                                    .build())
                            .build())
                    .save(ConfigManager::save)
                    .build()
                    .generateScreen(parent);
        };
    }
}